### ISSUE TITLE
Support `publishType` attribute

### ISSUE THREAD

**Issue by dev-gvs** [cianru/rustore-publish-gradle-plugin#13]
There is [`publishType`](https://www.rustore.ru/help/work-with-rustore-api/api-upload-publication-app/create-draft-version#%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B-%D0%B2%D0%B7%D0%B0%D0%B8%D0%BC%D0%BE%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F) attribute in the RuStore API. And then there is [`deployType`](https://github.com/cianru/rustore-publish-gradle-plugin/blob/29e805f4a6f318d0940eacaa4db1c1f940e61626/plugin/src/main/kotlin/ru/cian/rustore/publish/RustorePublishTask.kt#L48) parameter in the plugin, but it doesn't affect anything, as far as I could tell. I think it could be mapped to the `publishType` values from the RuStore API, and maybe renamed.

P.S.: Thank you for this awesome plugin!

**Comment by cosic** [comment]
Yes, I think we should support the release of the section https://www.rustore.ru/help/work-with-rustore-api/api-upload-publication-app/publishing-change-settings. We don't use it for RuStore. But let's collect likes 👍  for this request to understand how popular this feature request is.

**Comment by cosic** [comment]
@dev-gvs Hi! Please check and try `publishType` param into a new version plugin described in https://github.com/cianru/rustore-publish-gradle-plugin/issues/15#issuecomment-2395208355

**Comment by cosic** [comment]
@dev-gvs hi! Please update the plugin upto `0.5.1` release version. All alpha version will be removed.
