### ISSUE TITLE
Can't detect previous app versionId. Server response message must contain 'ID ='

### ISSUE THREAD

**Issue by lolka123455** [cianru/rustore-publish-gradle-plugin#14]
Приветствую, я использовал ваш плагин но почему то получаю ошибку -
`> Can't detect previous app versionId. Server response message must contain 'ID ='
`
Я видел решение этой проблемой добавив release note , но это не помогло (
Xотел уточнить возможно только я сталкиваюсь с этой проблемой на версии 0.5.0
Но мой json выглядит таким образом -

{
    "key_id": "1111111111",
    "client_secret": "MII........"
}

Я начал пробовать и подумал может быть формат записи JSON должен быть таким -

{
    "key_id": "<1111111111>",
    "client_secret": "<MII........>"
}

Но плагин падает на втором шаге с - `Illegal base64 character` , потому я вернул обратно

Вот логи -

Rustore Publishing API: Found build file: `app-release-unsigned.apk`
Rustore Publishing API: 2/6. Create signature
Rustore Publishing API: 3/6. Get Access Token
INFO, Rustore Publishing API: 
```
curl --location --request POST \
https://public-api.rustore.ru/public/auth/ \
--header 'Content-Type: application/json' \
--data-raw '{
    "keyId": "1111111111",
    "timestamp": "2024-09-25T14:22:07.5691421+03:00",
    "signature": "Uy........"
}'
```
Rustore Publishing API: 4/6. Create App Draft
INFO, Rustore Publishing API: 
```
curl --location --request POST \
https://public-api.rustore.ru/public/v1/application/com.example.test/version \
--header 'Content-Type: application/json' \
--header 'Public-Token: eyJlbm...... \
--data-raw '{
    "whatsNew": "Test"
}'
```

Реализация в гредле тоже стандартная - 

```
rustorePublish {
    instances {
        create("release") {
            credentialsPath = "$rootDir/rustore.json"
            deployType = DeployType.UPLOAD_ONLY
            buildFormat = BuildFormat.APK
            releaseNotes = listOf(
                ReleaseNote(
                    lang = "en-US",
                    filePath = "$projectDir/release-notes-ru.txt"
                ),
            )
        }
    }
}
```

PS так же в рустор была загружена прила руками и ей была присвоена версия , так что тут все ок.
Буду рад любой помощи или комментариям, заранее спасибо

**Comment by cosic** [comment]
@lolka123455 Привет! По какой-то причине API не может создать драфт релиза. Давайте попорядку

1. 
> Но мой json выглядит таким образом -
>
>{
>"key_id": "1111111111",
>"client_secret": "MII........"
>}

думаю с ключем все в порядке. На ошибку подписи API строго реагирует и быстро возвращает ошибку. Тут все ОК, подпись подошла. Единственное, если у вас несколько приложений, она может быть не от того приложения. 

2. Глаз цепляется за
>Rustore Publishing API: Found build file: app-release-unsigned.apk
Кажется вы пытаетесь залить не подписанное приложение. Это точно не причина ошибки, потому что до аплоада пока еще не дошло. Но проверьте этот момент. 

3. 
>INFO, Rustore Publishing API:

>curl --location --request POST \
>https://public-api.rustore.ru/public/v1/application/com.example.test/version \
>--header 'Content-Type: application/json' \
>--header 'Public-Token: eyJlbm...... \
>--data-raw '{
>    "whatsNew": "Test"
>}'

Тут насколько корректный запрос? Верно указан applicationID? Какую ошибку выдает curl?

**Comment by lolka123455** [comment]
applicationID указан верно. Но по поводу curl у меня сомнения как вы можете видеть то на шаге 4 , у нас будет такой curl -
```
curl --location --request POST 'https://public-api.rustore.ru/public/v1/application/com.example.test/version' \
--header 'Content-Type: application/json' \
--header 'Public-Token: eyJlbm...'
```
Сервер мне отвечает вот так -

`{
    "code": "ERROR",
    "message": "JSON parse error",
    "body": null,
    "timestamp": "2024-09-29T11:23:14.571837268Z"
}`

Я заметил что в запросе не передается versionId и тип (apk/aab), а так же добавляется хедер --header 'Content-Type: application/json',хотя в документации вроде ничего о нем не написано и сам путь до файла тоже отсутствует , как из примера документации -
`curl --location --request POST 'https://public-api.rustore.ru/public/v1/application/com.package.example/version/123/apk?servicesType=Unknown&isMainApk=true' \
--header 'Public-Token: {YOURtoken}' \
--form 'file=@"/Users/User/Downloads/package.apk"'`

Я зашел в постман и вот такой запрос работает корректно -
```
curl --location 'https://public-api.rustore.ru/public/v1/application/com.example.test/version/{versionId}/{apk/aab}' \
--header 'Public-Token: eyJlbm...' \
--form 'file=@"Путь к файлу"'
```

**Comment by cosic** [comment]
@lolka123455 
>Но по поводу curl у меня сомнения как вы можете видеть то на шаге 4 , у нас будет такой curl -
Нет. Как вы можете видеть из вашего первого сообщения, курл на 4м шаге будет с телом
```
Rustore Publishing API: 4/6. Create App Draft
INFO, Rustore Publishing API:

curl --location --request POST \
https://public-api.rustore.ru/public/v1/application/com.example.test/version \
--header 'Content-Type: application/json' \
--header 'Public-Token: eyJlbm...... \
--data-raw '{
    "whatsNew": "Test"
}'
```

>Я заметил что в запросе не передается versionId и тип (apk/aab), а так же добавляется хедер --header 'Content-Type: application/json',хотя в документации вроде ничего о нем не написано и сам путь до файла тоже отсутствует , как из примера документации -
curl --location --request POST 'https://public-api.rustore.ru/public/v1/application/com.package.example/version/123/apk?servicesType=Unknown&isMainApk=true' \ --header 'Public-Token: {YOURtoken}' \ --form 'file=@"/Users/User/Downloads/package.apk"'

Вы смотрите документацию другого метода. В нашей проблеме не проходит запрос [создания черновика версии](https://www.rustore.ru/help/work-with-rustore-api/api-upload-publication-app/create-draft-version). Вы смотрите документацияю [Загрузка APK файла](https://www.rustore.ru/help/work-with-rustore-api/api-upload-publication-app/apk-file-upload/file-upload-apk). Плагин выполнит этот запрос на 5м шаге. 

Давайте разбираться, почему не создается драфт черновика.

**Comment by lolka123455** [comment]
У меня есть два черновика , возможно проблема в этом, попробую их удалить. Подскажите пожалуйста если версия у черновика например - 1.2.3(12345) то что именно мы передаем в versionId?

**Comment by lolka123455** [comment]
Спасибо , что помогли мне разобраться со всем этим. Я создал черновик , потом удалил его. Так же выпустил новый ключ где дал ему все пермишены и все заработало. Ещё раз спасибо вам большое

**Comment by cosic** [comment]
@lolka123455 Отлично! Видимо дело было в ключе. Потому что на проблему существующего черновика я уже натыкался и [делал внутри плагина удаление и создание нового черновика под капотом](https://github.com/cianru/rustore-publish-gradle-plugin/blob/29e805f4a6f318d0940eacaa4db1c1f940e61626/plugin/src/main/kotlin/ru/cian/rustore/publish/service/RustoreServiceImpl.kt#L88).

**Comment by lolka123455** [comment]
@cosic Вы не могли бы проверить логику `DeployType.DRAFT` в aab.
Просто сейчас когда ты выставляешь `DeployType.DRAFT` то почему то черновик создается не как manual ,а как автоматически после модерации.
Хотя я ставил Draft и по логике публикация даже быть ручная

**Comment by lolka123455** [comment]
Кажется это все таки баг.
Вот код в гредле -
```
rustorePublish {
    instances {
        create("release") {
            credentialsPath = "$rootDir/rustore.json"
            deployType = DeployType.DRAFT
            buildFormat = BuildFormat.AAB
            releaseNotes = listOf(
                ReleaseNote(
                    lang = "ru-RU",
                    filePath = "$projectDir/release-notes-ru.txt"
                ),
            )
        }
    }
}
```

А вот лог -
`Rustore Publishing API: 4/6. Create App Draft
INFO, Rustore Publishing API: curl --location --request POST \
https://public-api.rustore.ru/public/v1/application/com.example.sobes/version \
--header 'Content-Type: application/json' \
--header 'Public-Token: eyJlbmM' \
--data-raw '{
    "whatsNew": "Test"
}'
`

Так же если посмотреть на [фаил](https://github.com/cianru/rustore-publish-gradle-plugin/blob/master/plugin/src/main/kotlin/ru/cian/rustore/publish/service/RustoreServiceImpl.kt) а именно на функцию createDraft , то там не передается параметр publishType и тк мы не передаем параметр publishType то по дэфолту он является [INSTANTLY](https://www.rustore.ru/help/work-with-rustore-api/api-upload-publication-app/create-draft-version)

Корректный curl для ручного создания черновика должен выглядеть, например вот так -
```
curl --location 'https://public-api.rustore.ru/public/v1/application/ru.test.test/version' \
--header 'Content-Type: application/json' \
--header 'Public-Token: eyJlbmM' \
--data '{
    "whatsNew": "Тест",
    "publishType": "MANUAL"
}'
```

**Comment by cosic** [comment]
@lolka123455 Могли бы вы пожалуйста завести новый issue и продублировать сообщения, чтобы не смешивать разные проблемы в одном?

**Comment by lolka123455** [comment]
@cosic да, без проблем)
