### ISSUE TITLE
Баг связанный с созданием черновика с ручной публикацией

### ISSUE THREAD

**Issue by lolka123455** [cianru/rustore-publish-gradle-plugin#15]
@cosic 
Вот код в гредле -
```
rustorePublish {
    instances {
        create("release") {
            credentialsPath = "$rootDir/rustore.json"
            deployType = DeployType.DRAFT
            buildFormat = BuildFormat.AAB
            releaseNotes = listOf(
                ReleaseNote(
                    lang = "ru-RU",
                    filePath = "$projectDir/release-notes-ru.txt"
                ),
            )
        }
    }
}
```

А вот лог -
`Rustore Publishing API: 4/6. Create App Draft
INFO, Rustore Publishing API: curl --location --request POST \
https://public-api.rustore.ru/public/v1/application/com.example.test/version \
--header 'Content-Type: application/json' \
--header 'Public-Token: eyJlbmM' \
--data-raw '{
    "whatsNew": "Test"
}'
`

Так же если посмотреть на [фаил](https://github.com/cianru/rustore-publish-gradle-plugin/blob/master/plugin/src/main/kotlin/ru/cian/rustore/publish/service/RustoreServiceImpl.kt) а именно на функцию createDraft , то там не передается параметр publishType и тк мы не передаем параметр publishType то по дэфолту он является [INSTANTLY](https://www.rustore.ru/help/work-with-rustore-api/api-upload-publication-app/create-draft-version)

Корректный curl для ручного создания черновика должен выглядеть, например вот так -
```
curl --location 'https://public-api.rustore.ru/public/v1/application/ru.test.test/version' \
--header 'Content-Type: application/json' \
--header 'Public-Token: eyJlbmM' \
--data '{
    "whatsNew": "Тест",
    "publishType": "MANUAL"
}'
```

**Comment by cosic** [comment]
@lolka123455 Привет. Попробуйте пожалуйста версию плагина `0.5.1-alpha01`. В ней добавлен параметр `publishType` со значением по умолчанию `INSTANTLY `:
```
/**
         * (Optional)
         * CLI: `--publishType`
         * ----| 'instantly' – the application will be published immediately after the review process is completed.
         * ----| 'manual' – the application must be published manually by the developer after ther review process is completed.
         * Gradle Extenion DSL, available values:
         * ----| ru.cian.rustore.publish.PublishType.INSTANTLY
         * ----| ru.cian.rustore.publish.PublishType.MANUAL
         * Default value: `instantly`
         */  
      publishType = ru.cian.rustore.publish.PublishType.INSTANTLY
```

**Comment by lolka123455** [comment]
@cosic Приветствую возможно вы допустили ошибку , вот так сейчас выглядит curl -
```
curl --location --request POST \
https://public-api.rustore.ru/public/v1/application/com.test.example/version \
--header 'Content-Type: application/json' \
--header 'Public-Token: eyJ' \
--data-raw '{
    "whatsNew": "Тест",
    "publishType:": "MANUAL"
}'
```

Обратите внимание тут у параметра `:` а его не должно быть -` "publishType:": "MANUAL"` 
Из за этого логика не работает

**Comment by cosic** [comment]
@lolka123455 

>Обратите внимание тут у параметра : а его не должно быть - "publishType:": "MANUAL"

Да, спасибо, я поправлю опечатку. Но `curl` выводится просто для информации, это просто лог. 

>Из за этого логика не работает

Вы уверены что плагин отработал некорректно?

**Comment by lolka123455** [comment]
Пока нет времени к сожалению , я перепроверю еще раз и напишу уже ответ в течении недели

**Comment by lolka123455** [comment]
@cosic Проблема осталась , возможно я использую не ту версию, моя версия `0.5.1-alpha01`
На всякий еще раз скидываю гредл -
```
rustorePublish {
    instances {
        create("liveRustoreRelease") {
            credentialsPath = CiVariables.RuStore.credentialsPath
            publishType = PublishType.MANUAL
            buildFormat = BuildFormat.AAB
            releaseNotes = listOf(
                ReleaseNote(
                    lang = "ru-RU",
                    filePath = "$rootDir/release-notes-ru.txt"
                ),
            )
        }
    }
}
```

Вот скрины из рустора при работе пайплайна -
![изображение](https://github.com/user-attachments/assets/b827df84-617f-481f-aeb9-1a779e5d5118)
![изображение](https://github.com/user-attachments/assets/0647c8e4-80ac-4a54-ac71-f1b885fe1b47)

**Comment by cosic** [comment]
@lolka123455 Попробуйте пожалуйста повторить с флагом `--refresh-dependencies`

**Comment by lolka123455** [comment]
@cosic К сожалению это так же почему то не помогло ( 
На вашей стороне все работает корректно ?

**Comment by cosic** [comment]
@lolka123455 Да, вы правы, нашел ошибку. Поправил в `0.5.1-alpha02`.

**Comment by lolka123455** [comment]
@cosic Подтверждаю , баг пропал. Исправлено

**Comment by cosic** [comment]
@lolka123455 @dev-gvs hi! Please update the plugin upto `0.5.1` release version. All alpha version will be removed.
