### ISSUE TITLE
Support of AAB files

### ISSUE THREAD

**Issue by cosic** [cianru/rustore-publish-gradle-plugin#9]
Appeared corresponding API in the Documentation https://www.rustore.ru/help/work-with-rustore-api/api-upload-publication-app/apk-file-upload/file-upload-aab 
Now we can support this feature.

**Comment by dev-gvs** [comment]
When this is planned to be released?

I see it's in snapshot-0.5.0 branch, but there's no release or snapshot version for it :thinking:

**Comment by cosic** [comment]
@dev-gvs Hi! Actually that's great you've asked about. I need your help. When I try to use RuStore API to upload aab file I've got the error:

```bash
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:publishRustoreRelease'.
> Build file uploading is failed! Reason code: ERROR, message: Jwe token is expired
```
The Rustore support team told me about connection problem from my side. But my collegues get the same error from different locations and internet providers. 

We need to try an other project to get a proofs. If you are ready to try than just update the plugin upto `0.5.0-alpha01` version and add a new row to the plugin extention

```kotlin
    configure<ru.cian.rustore.publish.RustorePublishExtension> {
        instances {
            register("release") {
                ...
                buildFormat = ru.cian.rustore.publish.BuildFormat.AAB // <-- that one! 
                ....
            }
        }
    }
```

Run 
```bash
./gradlew publishRustoreRelease
```
and say me your output result.

**Comment by dev-gvs** [comment]
@cosic The AAB file size is 114,7 MiB, and the output from publish task after ~4 minutes:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:publishRustoreLiveRuStoreRelease'.
> java.net.SocketTimeoutException: timeout
```

Setting the `requestTimeout` to higher value didn't help.

**Comment by cosic** [comment]
@dev-gvs To extend request timeout please add a new one row into the Plugin extention
```kotlin
    configure<ru.cian.rustore.publish.RustorePublishExtension> {
        instances {
            register("release") {
                ...
                buildFormat = ru.cian.rustore.publish.BuildFormat.AAB
                requestTimeout = 1800 // <-- this one, which equals to 30min;
                ....
            }
        }
    }
```

**Comment by cosic** [comment]
@dev-gvs How long the plugin do request before SocketTimeoutException? 

OK! Let's try `0.5.0-alpha02` version. I've aplied `requestTime` for readTimeout and writeTimeout too. 

If you will get a new error than just run publication task with `--info` flag. 
```
./gradlew publishRustoreRelease --info
```
In terminal output you will see raw `curl` command. You can use it without any timeout restrictions.

**Comment by dev-gvs** [comment]
@cosic the `0.5.0-alpha02` version actually works!

**Comment by cosic** [comment]
@dev-gvs Was your aab file published successfully?

**Comment by cosic** [comment]
@dev-gvs Wow! Deep inside I hoped that you will get the same error as me 😄. Well, I going to release this version to get a new feed back. Thx for your help.

**Comment by dev-gvs** [comment]
@cosic heh, we actually had some problems with RuStore recently (couldn't upload manually from their console), probably some error on their side. But now everything works. So, maybe this is related to your errors :thinking:

**Comment by cosic** [comment]
@dev-gvs Unfortunately not ((
```bash
* What went wrong:
Execution failed for task ':app:publishRustoreRelease'.
> Build file uploading is failed! Reason code: ERROR, message: Jwe token is expired
BUILD FAILED in 23m 10s
```
